name: Setup Masscan Environment

on:
  workflow_dispatch:

#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
#   schedule:
#     # 每周一的早上 8 点 (UTC 时间)
#     - cron: '0 8 * * 1'

jobs:
  setup-masscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Package List
        run: sudo apt-get update

      - name: Install Dependencies
        run: sudo apt-get install -y libpcap-dev

      - name: Install Masscan 
        run: sudo apt install masscan -y

      - name: Scan IP
        run:  sudo masscan -c myscan.conf

    #   - name: cat  scan.json
    #     run:  cat scan.json

      - name: Script Init
        run:  pip3 install requests

      - name: Run Python Script
        run: python3 ./parser.py

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
            git add README.md
            git commit -m "Update README via GitHub Actions"
            git push
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}