name: Setup Masscan Environment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-masscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Package List
        run: sudo apt-get update

      - name: Install Dependencies
        run: sudo apt-get install -y libpcap-dev

      - name: Install Masscan 
        run: sudo apt install masscan -y

      - name: Create Config File
        run: |
          echo "rate =  5000" > myscan.conf
          echo "output-format = xml" >> myscan.conf
          echo "output-status = open" >> myscan.conf
          echo "output-filename = scan.xml" >> myscan.conf
          echo "ports = 33445" >> myscan.conf
          echo "range = "61.141.76.0/24" >> myscan.conf

      - name: Scan IP
        run:  sudo masscan -c myscan.conf

      - name: cat  xml
        run:  cat scan.xml