name: Setup Masscan Environment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-masscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Package List
        run: sudo apt-get update

      - name: Install Dependencies
        run: sudo apt-get install -y libpcap-dev

      - name: Install Masscan 
        run: sudo apt install masscan -y

      - name: Scan Single IP
        run:  sudo masscan 182.61.200.6 -p 1-1000 --rate=1000